### ISSUE TITLE
Share baseclass not working

### ISSUE THREAD

**Issue by retardedHacker** [rdlowrey/auryn#125] opened 2015-10-17 16:04 UTC
``` php
abstract class Base {}

class A extends Base{}

$injector = new Auryn\Injector;
$injector->share(Base::class);

$a1 = $injector->make(A::class);
$a2 = $injector->make(A::class);

var_dump($a1 === $a2); //returns false
```

I expected this to return true.

**Comment by vlakarados** [comment] 2015-10-17 17:05
What exactly is `Base::class`

**Comment by kelunik** [comment] 2015-10-18 10:39
You're requesting a instance of `A` without one being available. `Base` isn't and instance of `A`. It doesn't work the other way round either, but it works if you create an alias then.

```php
class Base {}
class A extends Base {}

$injector = new Auryn\Injector;
$injector->share(A::class);
$injector->alias(Base::class, A::class);

$a1 = $injector->make(Base::class);
$a2 = $injector->make(Base::class);

var_dump($a1 === $a2);
```

**Comment by kelunik** [comment] 2017-01-09 12:04
Duplicate of #145, closing this one, as the other has more discussion.

**Closed by kelunik** 2017-01-09 12:04 UTC
